services:
  - type: web
    name: server
    runtime: docker
    repo: https://github.com/DodoBaboSent/kurs_go.git
    plan: free
    rootDir: server
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysql
          property: connectionString 
databases:
  - name: mysql
    databaseName: kurs